apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.serviceType }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.app.port }}
