image:
  repository: ghcr.io/mojojojo0222/todoapp
  tag: latest
  pullPolicy: Always

app:
  name: todoapp
  namespace: shipmate-todoapp
  replicas: 1
  port: 8080
  serviceType: NodePort
  healthPath: /actuator/health
  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 200m
      memory: 1536Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    cpuTarget: 60

db:
  engine: mysql
  storage: 20Gi
  port: 3306
